title: Wikmaps Atlas
name: "Wikimaps Atlas"
description: "A Wikimedia Foundation IEG Project"

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://planemad.github.io/wikimaps-atlas

paginate: 10

url: http://wikimapsatlas.github.io
baseurl: 


comments :
    provider : disqus
    disqus :
      short_name : wikimapsatlas
      
      
markdown: rdiscount
permalink: pretty
pygments: true push
