name: "Wikimaps Atlas"
description: "A Wikimedia Foundation IEG Project"


paginate: 10

url: "planemad.github.io"
BASE_PATH: "/wikimaps-atlas"

markdown: rdiscount
permalink: pretty
pygments: true push
